version: '3.3'
services:
  app:
    image: node:alpine3.13
    tty: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    command: sh -c 'yarn && yarn start'
    ports:
      - ${PORT}:80
    environment:
      - PORT=80
    working_dir: /app
    volumes:
      - ./:/app
